import { Dimensions, StyleSheet } from 'react-native';
import { theme } from '../theme';
import { getTextShadowStyle } from '../utils/styleUtils';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
    // NEW STYLES FOR UNIFIED DESIGN
    sectionContainer: {
        backgroundColor: theme.colors.white,
        borderRadius: 24,
        padding: 20,
        marginBottom: 24,
        marginHorizontal: 16,
        shadowColor: theme.colors.black,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 8,
        elevation: 2,
    },
    sectionTitleMain: {
        fontSize: 18,
        fontWeight: '700',
        color: theme.colors.text,
        marginBottom: 16,
        // marginStart: 4, // Removed for better alignment with cards
    },
    unifiedCard: {
        marginBottom: 8,
    },
    unifiedContent: {
        paddingVertical: 8,
    },
    divider: {
        height: 1,
        backgroundColor: theme.colors.borderLight,
        marginVertical: 16,
    },
    warningContainer: {
        backgroundColor: theme.colors.surfaceWashPink,
        borderRadius: theme.borderRadius.m,
        padding: 12,
        marginTop: 8,
    },
    postpartumBanner: {
        backgroundColor: theme.colors.surfaceOrangeTint,
        borderRadius: 24,
        padding: 20,
        marginHorizontal: 16,
        marginBottom: 24,
        flexDirection: 'row',
        alignItems: 'center',
        shadowColor: theme.colors.black,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 8,
        elevation: 2,
    },
    postpartumEmoji: {
        fontSize: 40,
        marginRight: 16,
    },
    postpartumTextContainer: {
        flex: 1,
    },
    postpartumTitle: {
        fontSize: 16,
        fontWeight: 'bold',
        color: theme.colors.orange900,
        marginBottom: 4,
    },
    postpartumDesc: {
        fontSize: 13,
        color: theme.colors.orange900,
        opacity: 0.9,
        lineHeight: 18,
        marginBottom: 12,
    },
    postpartumButton: {
        backgroundColor: theme.colors.orange500,
        paddingVertical: 8,
        paddingHorizontal: 16,
        borderRadius: 20,
        alignSelf: 'flex-start',
    },
    postpartumButtonText: {
        color: theme.colors.white,
        fontSize: 13,
        fontWeight: 'bold',
    },
    // EXISTING STYLES (Kept for compatibility)
    container: {
        flex: 1,
        backgroundColor: theme.colors.surface,
    },
    centerContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: theme.colors.surface,
        padding: 20,
    },
    errorEmoji: {
        fontSize: 48,
        marginBottom: 16,
    },
    headerGradient: {
        paddingTop: 60,
        paddingBottom: 60, // Increased to allow for overlap
        paddingHorizontal: 20,
        borderBottomLeftRadius: 30,
        borderBottomRightRadius: 30,
        shadowColor: theme.colors.black,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 8,
    },
    header: {
        width: '100%',
        paddingBottom: 24,
    },
    headerTextContainer: {
        alignItems: 'center',
        marginBottom: 16,
    },
    weekInfo: {
        fontSize: 14,
        color: theme.colors.whiteAlpha90,
        fontWeight: '500',
        marginTop: 4,
    },
    profileButtonContainer: {
        position: 'absolute',
        top: 16,
        right: 16,
        zIndex: 10,
    },
    profileButton: {
        width: 50,
        height: 50,
        borderRadius: 25,
        overflow: 'hidden',
        shadowColor: theme.colors.black,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 8,
    },
    profileGradient: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 3,
        borderColor: theme.colors.whiteAlpha50,
        borderRadius: 28,
    },
    profileButtonText: {
        color: theme.colors.white,
        fontWeight: 'bold',
        fontSize: 24,
    },
    centerContent: {
        alignItems: 'center',
        width: '100%',
    },
    greeting: {
        fontSize: 18,
        color: theme.colors.white,
        fontWeight: '600',
        marginBottom: 12,
        textAlign: 'center',
    },
    weekNavContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 8,
    },
    navButton: {
        paddingHorizontal: 12,
        paddingVertical: 4,
    },
    weekBadge: {
        alignItems: 'center',
        marginHorizontal: 16,
    },
    weekTitle: {
        fontSize: 28,
        fontWeight: 'bold',
        color: theme.colors.white,
        textAlign: 'center',
    },
    trimesterBadge: {
        fontSize: 12,
        color: theme.colors.whiteAlpha80,
        fontWeight: '600',
        marginTop: 4,
        backgroundColor: theme.colors.whiteAlpha20,
        paddingHorizontal: 8,
        paddingVertical: 2,
        borderRadius: 10,
    },
    weekSubtitle: {
        fontSize: 16,
        color: theme.colors.white,
        textAlign: 'center',
        fontWeight: '600',
        marginTop: 4,
    },
    progressContainer: {
        marginTop: 16,
        width: '100%',
        alignItems: 'center',
    },
    dayNavContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        width: '90%',
        justifyContent: 'space-between',
    },
    dayNavButton: {
        padding: 8,
        minWidth: 40,
        alignItems: 'center',
        justifyContent: 'center',
    },
    dayNavText: {
        fontSize: 28,
        color: theme.colors.white,
        fontWeight: 'bold',
    },
    progressBarWrapper: {
        flex: 1,
        alignItems: 'center',
        marginHorizontal: 8,
    },
    progressBar: {
        flexDirection: 'row',
        height: 10,
        width: '100%',
        backgroundColor: theme.colors.whiteAlpha20,
        borderRadius: 5,
        overflow: 'hidden',
    },
    progressSegment: {
        flex: 1,
        marginHorizontal: 1,
    },
    progressSegmentActive: {
        backgroundColor: theme.colors.white,
    },
    progressSegmentInactive: {
        backgroundColor: theme.colors.whiteAlpha30,
    },
    roundedLeft: {
        borderTopLeftRadius: 5,
        borderBottomLeftRadius: 5,
    },
    roundedRight: {
        borderTopRightRadius: 5,
        borderBottomRightRadius: 5,
    },
    progressText: {
        fontSize: 13,
        color: theme.colors.whiteAlpha90,
        marginTop: 8,
        fontWeight: '600',
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: theme.colors.blackAlpha60,
        justifyContent: 'flex-end',
    },
    personalDataModal: {
        backgroundColor: theme.colors.white,
        borderTopLeftRadius: 30,
        borderTopRightRadius: 30,
        maxHeight: '85%',
        shadowColor: theme.colors.black,
        shadowOffset: { width: 0, height: -4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 10,
    },
    modalHeader: {
        paddingTop: 32,
        paddingBottom: 24,
        paddingHorizontal: 24,
        alignItems: 'center',
        borderTopLeftRadius: 30,
        borderTopRightRadius: 30,
    },
    modalProfileCircle: {
        width: 80,
        height: 80,
        borderRadius: 40,
        backgroundColor: theme.colors.whiteAlpha30,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 4,
        borderColor: theme.colors.whiteAlpha50,
        marginBottom: 16,
    },
    modalProfileText: {
        fontSize: 36,
        fontWeight: 'bold',
        color: theme.colors.white,
    },
    modalName: {
        fontSize: 24,
        fontWeight: 'bold',
        color: theme.colors.white,
        marginBottom: 4,
    },
    modalEmail: {
        fontSize: 14,
        color: theme.colors.whiteAlpha90,
    },
    modalContent: {
        maxHeight: 400,
    },
    dataSection: {
        padding: 24,
        borderBottomWidth: 1,
        borderBottomColor: theme.colors.borderLight,
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: theme.colors.text,
        marginBottom: 16,
    },
    dataRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 12,
    },
    dataLabel: {
        fontSize: 15,
        color: theme.colors.textSecondary,
        flex: 1,
    },
    dataValue: {
        fontSize: 15,
        color: theme.colors.text,
        fontWeight: '600',
        flex: 1,
        textAlign: 'right',
    },
    highlightValue: {
        color: theme.colors.primary,
        fontWeight: 'bold',
    },
    modalActions: {
        flexDirection: 'row',
        padding: 16,
        borderTopWidth: 1,
        borderTopColor: theme.colors.borderLight,
        gap: 12,
    },
    modalActionButton: {
        flex: 1,
        flexDirection: 'column',
        alignItems: 'center',
        padding: 12,
        borderRadius: theme.borderRadius.m,
        backgroundColor: theme.colors.surface,
    },
    modalActionIcon: {
        fontSize: 24,
        marginBottom: 4,
    },
    modalActionText: {
        fontSize: 12,
        fontWeight: '600',
        color: theme.colors.text,
    },
    logoutButton: {
        backgroundColor: theme.colors.surfaceRose,
    },
    logoutText: {
        color: theme.colors.error,
    },
    contentContainer: {
        paddingBottom: 40, // Reduced from 100 to 40
    },
    quickNavContainer: {
        flexDirection: 'row',
        gap: 8,
        marginHorizontal: 16,
        marginTop: 12,
        marginBottom: 8,
        justifyContent: 'center',
    },
    quickNavButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: theme.colors.whiteAlpha25,
        borderRadius: theme.borderRadius.s,
        paddingVertical: 6,
        paddingHorizontal: 12,
        gap: 4,
        borderWidth: 1,
        borderColor: theme.colors.whiteAlpha40,
    },
    quickNavIcon: {
        fontSize: 12,
    },
    quickNavLabel: {
        fontSize: 11,
        fontWeight: '600',
        color: theme.colors.white,
    },
    quickLinksRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 12,
        marginBottom: 12,
        gap: 8,
    },
    quickLink: {
        fontSize: 11,
        color: theme.colors.white,
        fontWeight: '600',
        opacity: 0.9,
    },
    linkDivider: {
        fontSize: 10,
        color: theme.colors.white,
        opacity: 0.5,
    },
    quickActionsContainer: {
        flexDirection: 'row',
        gap: 10,
        marginHorizontal: 16,
        marginTop: 12,
        marginBottom: 16,
    },
    quickActionButton: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: theme.colors.white,
        borderRadius: theme.borderRadius.m,
        paddingVertical: 10,
        paddingHorizontal: 14,
        gap: 6,
        shadowColor: theme.colors.black,
        shadowOpacity: 0.15,
        shadowRadius: 4,
        shadowOffset: { width: 0, height: 2 },
        elevation: 3,
    },
    quickActionIcon: {
        fontSize: 16,
    },
    quickActionLabel: {
        fontSize: 13,
        fontWeight: '700',
        color: theme.colors.accent,
    },
    glassCard: {
        backgroundColor: theme.colors.white,
        borderRadius: theme.borderRadius.xl,
        padding: 20,
        marginBottom: 16,
        shadowColor: theme.colors.black,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 3,
    },
    quickFactsCard: {
        backgroundColor: theme.colors.surfaceBluePale,
        borderWidth: 1,
        borderColor: theme.colors.blue100,
    },
    factsSection: {
        marginTop: 4,
    },
    factItem: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        marginBottom: 12,
    },
    factIconContainer: {
        width: 32,
        height: 32,
        borderRadius: theme.borderRadius.l,
        backgroundColor: theme.colors.whiteAlpha80,
        justifyContent: 'center',
        alignItems: 'center',
        marginEnd: 12,
    },
    factIcon: {
        fontSize: 16,
    },
    factText: {
        flex: 1,
        fontSize: 15,
        color: theme.colors.text,
        lineHeight: 22,
    },
    cardTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: theme.colors.text,
        marginBottom: 12,
    },
    cardDescription: {
        fontSize: 15,
        color: theme.colors.neutral850,
        lineHeight: 22,
    },
    babyCard: {
        backgroundColor: theme.colors.lavenderBlush,
        borderWidth: 1,
        borderColor: theme.colors.borderPinkPastel,
    },
    babyHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 16,
    },
    babyInfo: {
        flex: 1,
    },
    babyStats: {
        flexDirection: 'row',
        gap: 12,
        marginTop: 8,
        marginBottom: 8,
    },
    statItem: {
        backgroundColor: theme.colors.primaryAlpha15,
        paddingHorizontal: 14,
        paddingVertical: 10,
        borderRadius: theme.borderRadius.m,
    },
    statLabel: {
        fontSize: 11,
        color: theme.colors.textLight,
        fontWeight: '600',
        textTransform: 'uppercase',
    },
    statValue: {
        fontSize: 18,
        fontWeight: 'bold',
        color: theme.colors.accent,
        marginTop: 2,
    },
    babyLabel: {
        fontSize: 14,
        color: theme.colors.textSecondary,
        fontStyle: 'italic',
    },
    emojiContainer: {
        width: 100,
        height: 100,
        backgroundColor: theme.colors.white,
        borderRadius: theme.borderRadius.xl,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: theme.colors.primary,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 6,
        elevation: 4,
    },
    emojiLarge: {
        fontSize: 52,
    },
    emojiWeek: {
        fontSize: 12,
        color: theme.colors.textLight,
        fontWeight: 'bold',
        marginTop: 4,
    },
    warningCard: {
        backgroundColor: theme.colors.surfaceAmberTint,
        borderWidth: 1,
        borderColor: theme.colors.amberBorder,
    },
    warningTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: theme.colors.accentOrangeDeep,
        marginBottom: 12,
    },
    appointmentItem: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: theme.colors.borderLight,
    },
    appointmentDate: {
        backgroundColor: theme.colors.surfaceBlueTint,
        borderRadius: 14,
        padding: 14,
        alignItems: 'center',
        marginEnd: 16,
        minWidth: 64,
    },
    appointmentDay: {
        fontSize: 26,
        fontWeight: 'bold',
        color: theme.colors.info,
    },
    appointmentMonth: {
        fontSize: 11,
        color: theme.colors.info,
        textTransform: 'uppercase',
        fontWeight: '600',
        marginTop: 2,
    },
    appointmentDetails: {
        flex: 1,
    },
    appointmentTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: theme.colors.text,
        marginBottom: 4,
    },
    appointmentTime: {
        fontSize: 14,
        color: theme.colors.textLight,
    },
    recommendationsList: {
        marginTop: 12,
        marginBottom: 16,
    },
    recommendationCard: {
        width: width * 0.45,
        minWidth: 180,
        height: 140,
        borderRadius: theme.borderRadius.l,
        overflow: 'hidden',
        shadowColor: theme.colors.black,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.15,
        shadowRadius: 6,
        elevation: 4,
    },
    recommendationGradient: {
        flex: 1,
        padding: 16,
        justifyContent: 'space-between',
    },
    recHeader: {
        alignSelf: 'flex-start',
    },
    recEmoji: {
        fontSize: 32,
    },
    recTitle: {
        fontSize: 15,
        fontWeight: 'bold',
        color: theme.colors.text,
        lineHeight: 20,
    },
    recSummary: {
        fontSize: 13,
        color: theme.colors.textSecondary,
        lineHeight: 18,
        marginTop: 6,
    },
    recBadge: {
        backgroundColor: theme.colors.whiteAlpha60,
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: theme.borderRadius.m,
        alignSelf: 'flex-start',
        marginTop: 8,
    },
    recBadgeText: {
        color: theme.colors.accent, // Dark Pink for better readability
        fontSize: 11,
        fontWeight: '700',
    },
    // ANTIGRAVITY: Tip Card Styles
    tipCard: {
        marginHorizontal: 16,
        marginBottom: 16,
        padding: 16,
        backgroundColor: theme.colors.surfaceTip,
        borderStartWidth: 4,
        borderStartColor: theme.colors.accentAmber,
    },
    tipHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 12,
    },
    tipEmoji: {
        fontSize: 24,
        marginEnd: 8,
    },
    tipTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: theme.colors.text,
    },
    tipShort: {
        fontSize: 15,
        fontWeight: '600',
        color: theme.colors.text,
        marginBottom: 8,
        lineHeight: 22,
    },
    tipLong: {
        fontSize: 14,
        color: theme.colors.textSecondary,
        lineHeight: 20,
        marginBottom: 12,
    },
    tipCategory: {
        backgroundColor: theme.colors.white,
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: theme.borderRadius.m,
        alignSelf: 'flex-start',
    },
    tipCategoryText: {
        fontSize: 12,
        color: theme.colors.accentOrangeDeep,
        fontWeight: '600',
    },

    // ==========================================
    // PREMIUM HERO CARD STYLES (Phase 1)
    // ==========================================
    heroCardGradient: {
        borderRadius: 24,
        padding: 24,
        marginTop: 12,
        shadowColor: theme.colors.shadowHeroPink,
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.15,
        shadowRadius: 16,
        elevation: 8,
    },
    heroEmojiContainer: {
        alignItems: 'center',
        marginBottom: 24,
    },
    heroEmoji: {
        fontSize: 64,
        marginBottom: 8,
        ...getTextShadowStyle(theme.colors.black, 0.1, 8, { width: 0, height: 4 }),
    },
    heroWeekText: {
        fontSize: 14,
        color: theme.colors.textSecondary,
        fontWeight: '500',
        letterSpacing: 0.5,
        textTransform: 'uppercase',
    },
    heroStatsRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 20,
    },
    heroStatCard: {
        backgroundColor: theme.colors.white,
        borderRadius: theme.borderRadius.l,
        paddingVertical: 12,
        paddingHorizontal: 16,
        width: '48%',
        alignItems: 'center',
        shadowColor: theme.colors.black,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 4,
        elevation: 2,
    },
    heroStatValue: {
        fontSize: 22,
        fontWeight: '800',
        color: theme.colors.coral,
        marginBottom: 4,
    },
    heroStatLabel: {
        fontSize: 13,
        color: theme.colors.textSecondary,
        fontWeight: '500',
    },
    heroComparisonBox: {
        backgroundColor: theme.colors.whiteAlpha60,
        borderRadius: theme.borderRadius.l,
        padding: 16,
        alignItems: 'center',
        marginBottom: 20,
        borderWidth: 1,
        borderColor: theme.colors.whiteAlpha80,
    },
    heroComparisonLabel: {
        fontSize: 14,
        color: theme.colors.textSecondary,
        marginBottom: 4,
    },
    heroComparisonValue: {
        fontSize: 18,
        fontWeight: '700',
        color: theme.colors.text,
        textAlign: 'center',
    },
    heroDevText: {
        fontSize: 15,
        color: theme.colors.textSecondary,
        lineHeight: 24,
        textAlign: 'center',
        paddingHorizontal: 8,
    },
    tipCardGradient: {
        borderRadius: theme.borderRadius.l,
        padding: 20,
        borderStartWidth: 4,
        borderStartColor: theme.colors.accentAmberDark,
        shadowColor: theme.colors.accentAmberDark,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 4,
    },
    // Premium Info Card (Cette semaine)
    infoCardPremium: {
        backgroundColor: theme.colors.white,
        borderRadius: theme.borderRadius.l,
        padding: 16,
        borderStartWidth: 4,
        borderStartColor: theme.colors.accentPurple,
        shadowColor: theme.colors.black,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 8,
        elevation: 2,
        marginBottom: 8,
    },
    /** Variante liste rouge à surveiller — bordure début logique (RTL-safe) */
    infoCardPremiumAlert: {
        borderStartColor: theme.colors.critical,
        borderWidth: 1,
        borderColor: theme.colors.surfaceRose,
    },
    infoCardHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 8,
    },
    infoCardEmoji: {
        fontSize: 20,
        marginEnd: 8,
    },
    infoCardTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: theme.colors.text,
    },
    infoCardText: {
        fontSize: 14,
        color: theme.colors.textSecondary,
        lineHeight: 22,
    },
    // Tools Grid
    toolsGrid: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        flexWrap: 'wrap',
        marginTop: 8,
    },
    toolCard: {
        width: '48%',
        backgroundColor: theme.colors.white,
        borderRadius: theme.borderRadius.l,
        padding: 16,
        alignItems: 'center',
        shadowColor: theme.colors.black,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 8,
        elevation: 2,
        marginBottom: 16,
    },
    toolIconContainer: {
        width: 48,
        height: 48,
        borderRadius: 24,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 12,
    },
    toolEmoji: {
        fontSize: 24,
    },
    toolTitle: {
        fontSize: 15,
        fontWeight: '600',
        color: theme.colors.text,
        marginBottom: 4,
    },
    toolSubtitle: {
        fontSize: 12,
        color: theme.colors.neutral400,
        textAlign: 'center',
    },

    // ==========================================
    // OLD STYLES (kept for compatibility)
    // ==========================================
    babySizeContainerPro: {
        marginTop: 16,
    },
    babySizeRowPro: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        marginBottom: 20,
        paddingHorizontal: 20,
    },
    babySizeStatPro: {
        alignItems: 'center',
        flex: 1,
    },
    babySizeLabelPro: {
        fontSize: 16,
        color: theme.colors.neutral400,
        marginBottom: 8,
        fontWeight: '400',
    },
    babySizeValuePro: {
        fontSize: 36,
        fontWeight: 'bold',
        color: theme.colors.coral, // Orange vif comme screenshot
    },
    babyComparisonContainerPro: {
        backgroundColor: theme.colors.surfacePinkWash,
        paddingVertical: 24,
        paddingHorizontal: 20,
        borderRadius: theme.borderRadius.m,
        alignItems: 'center',
        marginBottom: 20,
        marginHorizontal: 4,
    },
    babyComparisonEmoji: {
        fontSize: 48,
        marginBottom: 12,
    },
    babyComparisonLabelPro: {
        fontSize: 16,
        color: theme.colors.neutral400,
        marginBottom: 8,
    },
    babyComparisonValuePro: {
        fontSize: 28,
        fontWeight: 'bold',
        color: theme.colors.coral, // Orange vif
        textAlign: 'center',
    },
    babyDevTextPro: {
        fontSize: 15,
        color: theme.colors.text,
        lineHeight: 24,
        paddingHorizontal: 4,
    },
    // OLD STYLES (kept for compatibility)
    babySizeContainer: {
        marginTop: theme.spacing.m,
    },
    babySizeRow: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        marginBottom: theme.spacing.m,
    },
    babySizeStat: {
        alignItems: 'center',
        flex: 1,
    },
    babySizeLabel: {
        fontSize: 14,
        color: theme.colors.textLight,
        marginBottom: 4,
    },
    babySizeValue: {
        fontSize: 24,
        fontWeight: 'bold',
        color: theme.colors.primary,
    },
    babyComparisonContainer: {
        backgroundColor: theme.colors.lavenderBlush,
        padding: theme.spacing.m,
        borderRadius: theme.borderRadius.m,
        alignItems: 'center',
        marginBottom: theme.spacing.m,
    },
    babyComparisonLabel: {
        fontSize: 14,
        color: theme.colors.textLight,
        marginBottom: 4,
    },
    babyComparisonValue: {
        fontSize: 20,
        fontWeight: 'bold',
        color: theme.colors.primary,
    },
    babyDevText: {
        fontSize: 15,
        color: theme.colors.text,
        lineHeight: 22,
    },
});
