import { Platform, StyleSheet } from 'react-native';
import { theme } from '../theme';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: theme.colors.white,
    },
    scrollContent: {
        flexGrow: 1,
    },
    progressContainer: {
        height: 4,
        backgroundColor: theme.colors.surfacePinkSoft,
        marginTop: Platform.OS === 'ios' ? 50 : 20,
    },
    progressBar: {
        height: '100%',
        backgroundColor: theme.colors.primary,
        borderRadius: 2,
    },
    stepContentContainer: {
        padding: 24,
        paddingTop: 40,
        paddingBottom: 40,
        alignItems: 'center' as const,
    },
    stepContent: {
        flex: 1,
        padding: 24,
        paddingTop: 40,
    },
    stepEmoji: {
        fontSize: 64,
        marginBottom: 16,
    },
    stepTitle: {
        fontSize: 26,
        fontWeight: '700',
        color: theme.colors.neutral900,
        textAlign: 'center',
        marginBottom: 8,
        lineHeight: 34,
    },
    stepSubtitle: {
        fontSize: 16,
        color: theme.colors.textSecondary,
        textAlign: 'center',
        marginBottom: 32,
    },
    optionsContainer: {
        width: '100%',
        gap: 12,
    },
    optionCard: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: theme.colors.white,
        borderRadius: 16,
        padding: 20,
        borderWidth: 2,
        borderColor: theme.colors.surfacePinkSoft,
    },
    optionCardSelected: {
        borderColor: theme.colors.primary,
        backgroundColor: theme.colors.background,
    },
    optionEmoji: {
        fontSize: 32,
        marginEnd: 16,
    },
    optionText: {
        fontSize: 18,
        fontWeight: '600',
        color: theme.colors.neutral900,
    },
    methodSelector: {
        flexDirection: 'row',
        gap: 12,
        marginBottom: 24,
    },
    methodButton: {
        flex: 1,
        padding: 14,
        borderRadius: 12,
        backgroundColor: theme.colors.neutral100,
        alignItems: 'center',
    },
    methodButtonActive: {
        backgroundColor: theme.colors.surfacePinkSoft,
    },
    methodText: {
        fontSize: 14,
        fontWeight: '600',
        color: theme.colors.textSecondary,
    },
    methodTextActive: {
        color: theme.colors.accent,
    },
    dateSection: {
        width: '100%',
        alignItems: 'center',
    },
    dateLabel: {
        fontSize: 16,
        fontWeight: '600',
        color: theme.colors.neutral900,
        marginBottom: 12,
    },
    dateInput: {
        width: '100%',
        padding: 16,
        borderRadius: 12,
        borderWidth: 2,
        borderColor: theme.colors.pinkLightPastel,
        backgroundColor: theme.colors.white,
        alignItems: 'center',
    },
    dateText: {
        fontSize: 18,
        color: theme.colors.neutral900,
        fontWeight: '600',
    },
    previewBox: {
        marginTop: 20,
        padding: 16,
        backgroundColor: theme.colors.background,
        borderRadius: 12,
        alignItems: 'center',
    },
    previewLabel: {
        fontSize: 14,
        color: theme.colors.textSecondary,
    },
    previewWeek: {
        fontSize: 20,
        fontWeight: '700',
        color: theme.colors.accent,
        marginTop: 4,
    },
    previewSa: {
        fontSize: 16,
        color: theme.colors.textSecondary,
        marginTop: 4,
        fontWeight: '500',
    },
    inputGroup: {
        width: '100%',
        marginBottom: 24,
    },
    inputLabel: {
        fontSize: 16,
        fontWeight: '600',
        color: theme.colors.neutral900,
        marginBottom: 12,
    },
    textInput: {
        width: '100%',
        padding: 16,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: theme.colors.neutral200,
        backgroundColor: theme.colors.neutral25,
        fontSize: 16,
    },
    radioGroup: {
        gap: 10,
    },
    radioOption: {
        padding: 16,
        borderRadius: 12,
        borderWidth: 2,
        borderColor: theme.colors.neutral150,
        backgroundColor: theme.colors.neutral25,
    },
    radioOptionSelected: {
        borderColor: theme.colors.primary,
        backgroundColor: theme.colors.background,
    },
    radioText: {
        fontSize: 16,
        color: theme.colors.neutral900,
    },
    navButtons: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 16,
        marginTop: 32,
        width: '100%',
    },
    backButton: {
        padding: 16,
    },
    backButtonText: {
        fontSize: 16,
        color: theme.colors.textSecondary,
    },
    continueButton: {
        flex: 1,
    },
    // Final Screen Styles
    finalContainer: {
        flex: 1,
        minHeight: '100%',
    },
    finalContent: {
        width: '100%',
        padding: 32,
        paddingTop: 60,
        alignItems: 'center' as const,
    },
    finalEmoji: {
        fontSize: 80,
        marginBottom: 20,
    },
    finalGreeting: {
        fontSize: 28,
        fontWeight: '700',
        color: theme.colors.accent,
        marginBottom: 16,
        textAlign: 'center' as const,
    },
    finalWeekLabel: {
        fontSize: 16,
        color: theme.colors.textSecondary,
        marginBottom: 8,
        textAlign: 'center' as const,
    },
    weekBadge: {
        alignItems: 'center',
        marginBottom: 20,
    },
    weekNumber: {
        fontSize: 36,
        fontWeight: '800',
        color: theme.colors.neutral900,
    },
    dayNumber: {
        fontSize: 18,
        fontWeight: '600',
        color: theme.colors.textLight,
        marginTop: 4,
    },
    comparisonText: {
        fontSize: 18,
        color: theme.colors.textSecondary,
        textAlign: 'center',
        lineHeight: 26,
        marginBottom: 24,
    },
    divider: {
        width: 60,
        height: 2,
        backgroundColor: theme.colors.pinkLightPastel,
        marginVertical: 24,
    },
    emotionalText: {
        fontSize: 18,
        fontStyle: 'italic',
        color: theme.colors.textLight,
        textAlign: 'center',
        lineHeight: 28,
        marginBottom: 32,
    },
    startButton: {
        width: '100%',
        borderRadius: 16,
        overflow: 'hidden',
        shadowColor: theme.colors.accent,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 6,
    },
    startButtonGradient: {
        paddingVertical: 18,
        alignItems: 'center',
    },
    startButtonText: {
        fontSize: 18,
        fontWeight: '700',
        color: theme.colors.white,
    },
    backButtonFinal: {
        marginTop: 20,
        padding: 12,
    },
    finalScrollContent: {
        flexGrow: 1,
        alignItems: 'center' as const,
        justifyContent: 'center' as const,
    },
    accountSection: {
        width: '100%',
        marginBottom: 20,
    },
    accountTitle: {
        fontSize: 18,
        fontWeight: '700' as const,
        color: theme.colors.neutral900,
        textAlign: 'center' as const,
        marginBottom: 6,
    },
    accountSubtitle: {
        fontSize: 14,
        color: theme.colors.textSecondary,
        textAlign: 'center' as const,
        marginBottom: 16,
    },
    accountToggle: {
        flexDirection: 'row' as const,
        alignItems: 'center' as const,
        padding: 12,
        backgroundColor: theme.colors.white,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: theme.colors.pinkLightPastel,
    },
    checkbox: {
        width: 24,
        height: 24,
        borderRadius: 6,
        borderWidth: 2,
        borderColor: theme.colors.accent,
        marginEnd: 12,
        alignItems: 'center' as const,
        justifyContent: 'center' as const,
    },
    checkboxChecked: {
        backgroundColor: theme.colors.accent,
    },
    checkmark: {
        color: theme.colors.white,
        fontSize: 14,
        fontWeight: 'bold' as const,
    },
    accountToggleText: {
        fontSize: 14,
        color: theme.colors.neutral900,
        flex: 1,
    },
    accountFields: {
        marginTop: 12,
        gap: 10,
    },
    accountInput: {
        backgroundColor: theme.colors.white,
        borderRadius: 12,
        padding: 14,
        fontSize: 16,
        borderWidth: 1,
        borderColor: theme.colors.pinkLightPastel,
        color: theme.colors.neutral900,
        marginTop: 10,
        width: '100%',
    },
    accountNote: {
        fontSize: 12,
        color: theme.colors.textLight,
        textAlign: 'center' as const,
        marginTop: 8,
    },
    skipAccountButton: {
        marginTop: 12,
        padding: 14,
        alignItems: 'center' as const,
    },
    skipAccountText: {
        fontSize: 15,
        color: theme.colors.textLight,
        textDecorationLine: 'underline' as const,
    },
    ageRangeContainer: {
        flexDirection: 'row' as const,
        flexWrap: 'wrap' as const,
        gap: 10,
        justifyContent: 'center' as const,
    },
    ageRangeButton: {
        paddingVertical: 12,
        paddingHorizontal: 20,
        borderRadius: 20,
        backgroundColor: theme.colors.white,
        borderWidth: 2,
        borderColor: theme.colors.pinkLightPastel,
        minWidth: 70,
        alignItems: 'center' as const,
    },
    ageRangeButtonSelected: {
        backgroundColor: theme.colors.accent,
        borderColor: theme.colors.accent,
    },
    ageRangeText: {
        fontSize: 15,
        fontWeight: '600' as const,
        color: theme.colors.accent,
    },
    ageRangeTextSelected: {
        color: theme.colors.white,
    },
    startButtonDisabled: {
        opacity: 0.6,
    },
    // TTC Flow Styles
    cycleLengthContainer: {
        flexDirection: 'row' as const,
        alignItems: 'center' as const,
        justifyContent: 'center' as const,
        gap: 20,
        marginTop: 12,
    },
    cycleButton: {
        width: 50,
        height: 50,
        borderRadius: 25,
        backgroundColor: theme.colors.surfacePinkSoft,
        alignItems: 'center' as const,
        justifyContent: 'center' as const,
        borderWidth: 2,
        borderColor: theme.colors.primary,
    },
    cycleButtonText: {
        fontSize: 28,
        color: theme.colors.accent,
        fontWeight: '600' as const,
    },
    cycleLengthDisplay: {
        alignItems: 'center' as const,
        minWidth: 80,
    },
    cycleLengthNumber: {
        fontSize: 48,
        fontWeight: '700' as const,
        color: theme.colors.accent,
    },
    cycleLengthLabel: {
        fontSize: 14,
        color: theme.colors.textSecondary,
        marginTop: -4,
    },
    ttcInfoBox: {
        backgroundColor: theme.colors.background,
        borderRadius: 16,
        padding: 20,
        marginVertical: 16,
        borderWidth: 2,
        borderColor: theme.colors.surfacePinkSoft,
        alignItems: 'center' as const,
    },
    ttcInfoTitle: {
        fontSize: 16,
        fontWeight: '600' as const,
        color: theme.colors.neutral900,
        marginBottom: 8,
    },
    ttcInfoDate: {
        fontSize: 22,
        fontWeight: '700' as const,
        color: theme.colors.accent,
    },
    ttcInfoNote: {
        fontSize: 13,
        color: theme.colors.textSecondary,
        marginTop: 4,
    },
    ttcMessage: {
        fontSize: 16,
        color: theme.colors.textSecondary,
        textAlign: 'center' as const,
        lineHeight: 24,
        marginTop: 8,
    },
    // Curious Flow Styles
    exploreSection: {
        alignItems: 'center' as const,
        marginVertical: 24,
    },
    exploreSemaine: {
        fontSize: 42,
        fontWeight: '700' as const,
        color: theme.colors.accent,
    },
    exploreComparison: {
        fontSize: 18,
        color: theme.colors.textSecondary,
        marginTop: 8,
    },
    sliderContainer: {
        flexDirection: 'row' as const,
        alignItems: 'center' as const,
        width: '100%',
        marginTop: 24,
        gap: 12,
    },
    sliderButton: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: theme.colors.surfacePinkSoft,
        alignItems: 'center' as const,
        justifyContent: 'center' as const,
        borderWidth: 2,
        borderColor: theme.colors.primary,
    },
    sliderButtonText: {
        fontSize: 24,
        color: theme.colors.accent,
        fontWeight: '600' as const,
    },
    sliderTrack: {
        flex: 1,
        height: 8,
        backgroundColor: theme.colors.surfacePinkSoft,
        borderRadius: 4,
        overflow: 'hidden' as const,
    },
    sliderFill: {
        height: '100%',
        backgroundColor: theme.colors.primary,
        borderRadius: 4,
    },
    trimesterLabels: {
        flexDirection: 'row' as const,
        justifyContent: 'space-between' as const,
        width: '100%',
        marginTop: 8,
        paddingHorizontal: 56,
    },
    trimesterLabel: {
        fontSize: 12,
        color: theme.colors.neutral400,
        fontWeight: '500' as const,
    },
    curiousInfoBox: {
        backgroundColor: theme.colors.blueTintVeryPale,
        borderRadius: 16,
        padding: 20,
        marginVertical: 16,
        borderWidth: 2,
        borderColor: theme.colors.blueTintPale,
    },
    curiousInfoText: {
        fontSize: 14,
        color: theme.colors.neutral700,
        lineHeight: 24,
    },
    iosPickerOverlay: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: theme.colors.blackAlpha40,
        justifyContent: 'flex-end',
        borderTopStartRadius: 24,
        borderTopEndRadius: 24,
        overflow: 'hidden',
    },
    iosPickerContent: {
        backgroundColor: theme.colors.white,
        height: 300,
        paddingBottom: 20,
    },
    iosPickerHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingVertical: 16,
        borderBottomWidth: 1,
        borderBottomColor: theme.colors.disabled,
        backgroundColor: theme.colors.neutral25,
    },
    iosPickerTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: theme.colors.neutral900,
    },
    iosPickerDoneText: {
        fontSize: 16,
        fontWeight: '700',
        color: theme.colors.accent,
    },
});
