import { StyleSheet } from 'react-native';
import { theme } from '../theme';
import { getShadowStyle } from '../utils/styleUtils';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: theme.colors.neutral100,
    },
    content: {
        padding: 16,
        paddingBottom: 40,
    },
    header: {
        marginBottom: 20,
    },
    title: {
        fontSize: 28,
        fontWeight: '800',
        color: theme.colors.neutral900,
    },
    subtitle: {
        fontSize: 14,
        color: theme.colors.neutral700, // Improved contrast
    },
    currentWeight: {
        fontSize: 48,
        fontWeight: '800',
        color: theme.colors.neutral900,
    },
    weightGain: {
        fontSize: 16,
        color: theme.colors.textSecondary,
        marginTop: 4,
    },
    statusBadge: {
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: 20,
        marginTop: 12,
    },
    badgeNormal: {
        backgroundColor: theme.colors.surfaceGreenTint,
    },
    badgeLow: {
        backgroundColor: theme.colors.surfaceOrangeTint,
    },
    badgeHigh: {
        backgroundColor: theme.colors.surfaceOrangeTint,
    },
    badgeWarning: {
        backgroundColor: theme.colors.surfaceOrangeTint,
    },
    statusBadgeText: {
        fontSize: 14,
        fontWeight: '600',
        color: theme.colors.neutral900,
    },
    statusMessage: {
        fontSize: 14,
        color: theme.colors.textSecondary,
        marginTop: 8,
        textAlign: 'center',
    },
    noDataText: {
        fontSize: 16,
        color: theme.colors.neutral400,
        fontStyle: 'italic',
    },
    infoCard: {
        backgroundColor: theme.colors.surfaceBlueTint,
        borderRadius: 16,
        padding: 16,
        marginBottom: 16,
    },
    infoHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 8,
    },
    infoButton: {
        width: 24,
        height: 24,
        borderRadius: 12,
        backgroundColor: theme.colors.blue800,
        justifyContent: 'center',
        alignItems: 'center',
    },
    infoButtonText: {
        color: theme.colors.white,
        fontSize: 14,
        fontWeight: '700',
    },
    infoTitle: {
        fontSize: 16,
        fontWeight: '700',
        color: theme.colors.blue800,
    },
    infoText: {
        fontSize: 15,
        color: theme.colors.neutral900,
    },
    infoBold: {
        fontWeight: '700',
        color: theme.colors.blue800,
    },
    infoSubtext: {
        fontSize: 13,
        color: theme.colors.textSecondary,
        marginTop: 4,
    },
    infoDetail: {
        fontSize: 13,
        color: theme.colors.textSecondary,
        marginTop: 8,
    },
    infoIcon: {
        fontSize: 16,
    },
    bmiInfo: {
        fontSize: 13,
        color: theme.colors.textSecondary,
        marginTop: 8,
        fontStyle: 'italic',
    },
    /* PERFECT-FIX-2: BMI + OMS category row inside infoCard */
    bmiRow: {
        flexDirection: 'row',
        alignItems: 'center',
        flexWrap: 'wrap',
        marginTop: 6,
        gap: 8,
    },
    bmiLabel: {
        fontSize: 14,
        color: theme.colors.neutral900,
        fontWeight: '600',
    },
    bmiValue: {
        fontSize: 14,
        color: theme.colors.blue800,
        fontWeight: '800',
    },
    bmiCategoryBadge: {
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 999,
        borderWidth: 1,
    },
    bmiCategoryText: {
        fontSize: 12,
        fontWeight: '700',
    },
    chartContainer: {
        backgroundColor: theme.colors.white,
        borderRadius: 16,
        padding: 16,
        marginBottom: 16,
        ...getShadowStyle(2, theme.colors.black, 0.05, 4, { width: 0, height: 1 }),
    },
    chartTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: theme.colors.neutral900,
        marginBottom: 12,
    },
    chartYAxis: {
        position: 'absolute',
        left: 0,
        top: 0,
        bottom: 30,
        justifyContent: 'space-between',
        width: 35,
    },
    chartYLabel: {
        fontSize: 10,
        color: theme.colors.neutral400,
    },
    chartArea: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        height: 140,
        alignItems: 'flex-end',
        paddingStart: 40,
        paddingBottom: 25,
    },
    chartBar: {
        alignItems: 'center',
        flex: 1,
        height: '100%',
        position: 'relative',
    },
    chartColumn: {
        flex: 1,
        width: '100%',
        position: 'relative',
    },
    chartDot: {
        position: 'absolute',
        left: '50%',
        marginStart: -16,
        width: 32,
        height: 22,
        borderRadius: 11,
        justifyContent: 'center',
        alignItems: 'center',
    },
    dotLabel: {
        fontSize: 10,
        fontWeight: '600',
        color: theme.colors.white,
    },
    dotNormal: {
        backgroundColor: theme.colors.green500,
    },
    dotWarning: {
        backgroundColor: theme.colors.orange500,
    },
    chartLabel: {
        position: 'absolute',
        bottom: 0,
        fontSize: 11,
        color: theme.colors.textSecondary,
        fontWeight: '500',
    },
    chartStartRef: {
        marginTop: 12,
        paddingTop: 8,
        borderTopWidth: 1,
        borderTopColor: theme.colors.neutral150,
    },
    startRefText: {
        fontSize: 12,
        color: theme.colors.textLight,
        textAlign: 'center',
    },
    chartLegend: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 24,
    },
    legendText: {
        fontSize: 11,
        color: theme.colors.neutral400,
    },
    addButton: {
        backgroundColor: theme.colors.primary,
        borderRadius: 16,
        padding: 18,
        alignItems: 'center',
        marginBottom: 20,
    },
    addButtonText: {
        color: theme.colors.white,
        fontSize: 16,
        fontWeight: '700',
    },
    statusCard: {
        backgroundColor: theme.colors.white,
        borderRadius: 16,
        padding: 24,
        marginBottom: 20,
        ...getShadowStyle(2),
    },
    // SIMPLIFIED STYLES
    weightDisplay: {
        backgroundColor: theme.colors.white,
        borderRadius: 16,
        padding: 32,
        marginBottom: 20,
        alignItems: 'center',
        ...getShadowStyle(1),
    },
    hugeWeight: {
        fontSize: 64,
        fontWeight: '900',
        color: theme.colors.textInk,
        marginBottom: 8,
    },
    weightMeta: {
        alignItems: 'center',
        marginBottom: 24,
    },
    weightGainText: {
        fontSize: 14,
        color: theme.colors.neutral400,
        marginBottom: 4,
    },
    miniStatus: {
        fontSize: 13,
        color: theme.colors.accentOrangeDeep,
        marginTop: 4,
    },
    gaugeContainer: {
        width: '100%',
        marginTop: 16,
    },
    gaugeLabel: {
        fontSize: 12,
        color: theme.colors.neutral400,
        marginBottom: 8,
        textAlign: 'center',
    },
    gaugeBar: {
        height: 8,
        backgroundColor: theme.colors.disabled,
        borderRadius: 4,
        position: 'relative',
        marginBottom: 12,
    },
    gaugeRange: {
        position: 'absolute',
        left: '10%',
        right: '10%',
        height: '100%',
        backgroundColor: theme.colors.green500,
        borderRadius: 4,
        opacity: 0.3,
    },
    gaugeDot: {
        position: 'absolute',
        width: 20,
        height: 20,
        borderRadius: 10,
        backgroundColor: theme.colors.blue600,
        top: -6,
        marginStart: -10,
        borderWidth: 3,
        borderColor: theme.colors.white,
    },
    gaugeLabels: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    gaugeLabelText: {
        fontSize: 12,
        color: theme.colors.textSecondary,
        fontWeight: '600',
    },
    gaugeIcon: {
        fontSize: 18,
    },
    addForm: {
        backgroundColor: theme.colors.white,
        borderRadius: 16,
        padding: 20,
        marginBottom: 20,
        ...getShadowStyle(4, theme.colors.black, 0.1, 8, { width: 0, height: 2 }),
    },
    addFormTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: theme.colors.neutral900,
        marginBottom: 16,
    },
    inputRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 16,
    },
    weightInput: {
        flex: 1,
        borderWidth: 2,
        borderColor: theme.colors.primary,
        borderRadius: 12,
        padding: 16,
        fontSize: 24,
        fontWeight: '700',
        textAlign: 'center',
    },
    kgLabel: {
        fontSize: 20,
        fontWeight: '600',
        color: theme.colors.textSecondary,
        marginStart: 12,
    },
    formButtons: {
        flexDirection: 'row',
        gap: 12,
    },
    cancelButton: {
        flex: 1,
        padding: 14,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: theme.colors.neutral200,
        alignItems: 'center',
    },
    cancelButtonText: {
        fontSize: 16,
        fontWeight: '600',
        color: theme.colors.textSecondary,
    },
    saveButton: {
        flex: 1,
        padding: 14,
        borderRadius: 12,
        backgroundColor: theme.colors.primary,
        alignItems: 'center',
    },
    saveButtonDisabled: {
        opacity: 0.5,
    },
    saveButtonText: {
        fontSize: 16,
        fontWeight: '600',
        color: theme.colors.white,
    },
    historySection: {
        marginBottom: 20,
    },
    historyTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: theme.colors.neutral900,
        marginBottom: 12,
    },
    emptyHistory: {
        fontSize: 14,
        color: theme.colors.neutral400,
        fontStyle: 'italic',
        textAlign: 'center',
        padding: 20,
    },
    historyItem: {
        backgroundColor: theme.colors.white,
        borderRadius: 12,
        padding: 16,
        marginBottom: 8,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    historyLeft: {},
    historyWeight: {
        fontSize: 18,
        fontWeight: '700',
        color: theme.colors.neutral900,
    },
    historyDate: {
        fontSize: 13,
        color: theme.colors.textLight,
        marginTop: 2,
    },
    historyRight: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    historyBadge: {
        width: 28,
        height: 28,
        borderRadius: 14,
        justifyContent: 'center',
        alignItems: 'center',
    },
    historyBadgeText: {
        fontSize: 14,
        fontWeight: '700',
    },
    deleteButton: {
        padding: 8,
    },
    deleteButtonText: {
        fontSize: 16,
    },
    disclaimer: {
        backgroundColor: theme.colors.surfaceAmberTint,
        borderRadius: 12,
        padding: 12,
        borderWidth: 1,
        borderColor: theme.colors.amberBorder,
    },
    disclaimerText: {
        fontSize: 12,
        color: theme.colors.accentOrangeDeep,
        lineHeight: 18,
    },
    // Education section styles
    educationHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        backgroundColor: theme.colors.white,
        borderRadius: 12,
        padding: 16,
        marginBottom: 12,
    },
    educationHeaderText: {
        fontSize: 16,
        fontWeight: '700',
        color: theme.colors.neutral900,
    },
    educationToggle: {
        fontSize: 12,
        color: theme.colors.neutral400,
    },
    educationContent: {
        marginBottom: 16,
    },
    eduCard: {
        backgroundColor: theme.colors.white,
        borderRadius: 12,
        padding: 16,
        marginBottom: 12,
    },
    eduCardImportant: {
        backgroundColor: theme.colors.surfaceGreenTint,
        borderWidth: 1,
        borderColor: theme.colors.surfaceGreenBorder,
    },
    eduCardTitle: {
        fontSize: 15,
        fontWeight: '700',
        color: theme.colors.neutral900,
        marginBottom: 8,
    },
    eduCardText: {
        fontSize: 14,
        color: theme.colors.neutral700,
        lineHeight: 20,
    },
    eduBold: {
        fontWeight: '700',
        color: theme.colors.pinkAccent,
    },
    eduTable: {
        marginTop: 8,
    },
    eduTableRow: {
        flexDirection: 'row',
        paddingVertical: 6,
        borderBottomWidth: 1,
        borderBottomColor: theme.colors.borderLight,
    },
    eduTableHeader: {
        flex: 1,
        fontSize: 12,
        fontWeight: '700',
        color: theme.colors.textSecondary,
    },
    eduTableCell: {
        flex: 1,
        fontSize: 13,
        color: theme.colors.neutral900,
    },
    eduTips: {
        marginTop: 10,
    },
    eduTip: {
        fontSize: 14,
        color: theme.colors.neutral900,
        marginBottom: 4,
    },
    // Setup form styles
    setupCard: {
        backgroundColor: theme.colors.white,
        borderRadius: 20,
        padding: 24,
        marginBottom: 16,
        borderWidth: 2,
        borderColor: theme.colors.primary,
    },
    setupTitle: {
        fontSize: 20,
        fontWeight: '700',
        color: theme.colors.neutral900,
        marginBottom: 8,
    },
    setupDescription: {
        fontSize: 14,
        color: theme.colors.textSecondary,
        marginBottom: 20,
        lineHeight: 20,
    },
    setupField: {
        marginBottom: 16,
    },
    setupLabel: {
        fontSize: 14,
        fontWeight: '600',
        color: theme.colors.neutral900,
        marginBottom: 8,
    },
    setupInput: {
        borderWidth: 2,
        borderColor: theme.colors.disabled,
        borderRadius: 12,
        padding: 16,
        fontSize: 18,
        fontWeight: '600',
        textAlign: 'center',
        backgroundColor: theme.colors.neutral75,
    },
    setupButton: {
        backgroundColor: theme.colors.primary,
        borderRadius: 12,
        padding: 16,
        alignItems: 'center',
        marginTop: 8,
    },
    setupButtonText: {
        color: theme.colors.white,
        fontSize: 16,
        fontWeight: '700',
    },
    setupNote: {
        fontSize: 12,
        color: theme.colors.textLight,
        marginTop: 16,
        textAlign: 'center',
        lineHeight: 18,
    },
    // Demo mode styles
    demoButton: {
        backgroundColor: theme.colors.borderLight,
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: 20,
        marginTop: 12,
        alignSelf: 'center',
    },
    demoButtonActive: {
        backgroundColor: theme.colors.surfacePeach,
        borderWidth: 1,
        borderColor: theme.colors.orange500,
    },
    demoButtonText: {
        fontSize: 14,
        fontWeight: '600',
        color: theme.colors.textSecondary,
    },
    demoWarning: {
        fontSize: 12,
        color: theme.colors.orange500,
        textAlign: 'center',
        marginTop: 8,
        fontStyle: 'italic',
    },
    // ── IA locale intelligence block styles ──
    intelligenceCard: {
        backgroundColor: theme.colors.white,
        borderRadius: 16,
        padding: 16,
        marginBottom: 12,
        shadowColor: theme.colors.black,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.07,
        shadowRadius: 6,
        elevation: 2,
    },
    trimesterBanner: {
        backgroundColor: theme.colors.surfacePinkTint,
        borderRadius: 10,
        padding: 12,
        marginBottom: 12,
    },
    trimesterBannerText: {
        fontSize: 14,
        color: theme.colors.deepPink,
        lineHeight: 20,
        fontStyle: 'italic',
    },
    trendBadge: {
        borderWidth: 1,
        borderRadius: 10,
        padding: 10,
        marginBottom: 12,
    },
    trendText: {
        fontSize: 14,
        fontWeight: '600',
        textAlign: 'center',
    },
    suggestionsGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 8,
        marginTop: 4,
    },
    suggestionChip: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: theme.colors.surfacePurpleTint,
        borderRadius: 20,
        paddingHorizontal: 12,
        paddingVertical: 6,
        gap: 4,
    },
    suggestionIcon: {
        fontSize: 16,
    },
    suggestionText: {
        fontSize: 12,
        color: theme.colors.purpleDark,
        fontWeight: '500',
        flexShrink: 1,
    },
});
